### ISSUE TITLE
Wallet unlocks itself occasionally when mining with securestring password

### ISSUE THREAD

**Issue by biblepay** [biblepay/biblepay#62] opened 2018-12-27 14:57 UTC
Dave_BBP has reported the wallet sometimes unlocks itself when using the PODCunlock password feature.

He is running win10 with 4 mining threads.

     The problem occurs in my Windows 10 Pro wallet (x64), currently version 71 (but not limited to that version). The config looks like this:
Code:
shrinkdebug=1
gen=1
genproclimit=4
minersleep=1000
#utxooverride=1463000
#privatesendamount=20000
#testnet=1
pool=https://pool.purepool.org
workerid=B6fo71xAUr2gy2EBxVV69kUDxj7CH6CUXt/pc
#pool=https://pool.biblepay.org
#workerid=dave_pc

**Comment by MIPPL** [comment] 2018-12-28 11:14
I'll take a look at it. The fact that it happens "occasionally" makes things harder... If someone finds a deterministic way to reproduce this, please report here.

**Comment by MIPPL** [comment] 2018-12-29 18:57
I could not reproduce the problem but I found that if a SignStake call fails for whatever reason, wallet may be left unlocked. This would explain the apparent randomness of the issue.

Fix is in commit https://github.com/biblepay/biblepay/commit/f63bfff77ae628eed60dd86defc0a6f4f524190b 

And will be merged into master soon

**Closed by MIPPL** 2018-12-29 18:57 UTC
